cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "ci/hercules/derivations",
  "ci/hercules/effects",
  "ci/hercules/evaluation",
  # not a required status check
  "terraform-deploy",
]
