nix-community-cachix: ENC[AES256_GCM,data:tGMaYSBnhZ9idMV7DGzUfR1Zzk70syR8f4DSkrO65XcYUvoS4tcaVXr4l6PzDAFetkgU92a/kkIrEMZ9tZZZGHMvmCteGObH2BgF6k57NdozNnkXsI4ZhltATu5tpwzI+DUFgtpAXPEVYY6DRDlUATrt8SKJ2JuI4JtpIHpPi0noS/WpBfsphOUQ/7epTtABLpyDb0EOXisvkPLjDIKwfNDE+dOHO61aN8zS14QhelRIfJUSj7BwVFWbaseLKmq5ZIDAFK5s/FSgToi4Bj/YYVrTo23RH8wvhYOelSNcAWW/wotMZ5u/pklTytytLC41DhyFXU54k/UEorfVMHMnLAlujDoBs/9oV+M18Jcs0qV7c1utzjwoGlYhxV7zV/QvJ2zuMyDtszK0twcL8BjUSpsy+W/sR3kpGBKzjt1oNteTlz0YvIXlxg/Yn63qGr2/HzZlNd9rygMnLhTf7VO4Su2AB4GLXI7ljgQdqM7AREuAgE5J0hHE82fRalBsZcK34QGEFVKN4mzybcK4HO70yUQY4o5cOc7R5DHvEJmukjjJclm/,iv:N/yKtyd56YpdpNEe92g9Eml8gYR9x5pBT66U5p20Rzw=,tag:HCAJSqQ3Wq5SnZDwdryN1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYkk1bEdDN0FnZ0tYSEJS
            d3NPV0QrWmdMMWt0WmVNbkY2MXF4UUQzeG1rCkcyZnJ4YTMydjlESFZoa29tSnEv
            TVhZblphbGpRWVpab1VEZVBpaGM0a2sKLS0tIHlyRmo5Z21GREpHQkNGK1BYcXdP
            WFdwWnpsSnFGZkZhbzFjUE9EdjZmVDAKMkl6SxRIIVsfjYr9GhZEMJJBHn9D6esU
            NbM1hKVLqvl08Xrl0b3glxoTs3Seirbj9qj1jl65WwgqlZJyw93ZeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d87z3zqlv6ullnzyng8l722xzxwqr677csacf3zf3l28dau7avfs6pc7ay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVmg5b1ZXRmhwM25naE56
            NGV5RFExYmZXbThxbmdVZC95R1NJcmw1VnhNCmhPQWM0YWxTL3NJbjFsekpkclND
            M1hLNWZ4Wk95SXZDYmlFb1hNUUk2R28KLS0tIHk5SUpRUnA3WjB4YS9FQm1sOHU5
            U3Y5eXZhenFna0tIbjErVXZtRmFtbTQKjTh3xkEelFwjpBPxcf7o25pOTvAaz3mr
            NGACvPbDy2lqivzkLnGclv905/O3b2E29Np2N8Pj+/sVFJPRH8fPYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17jtyn2y4fpey6q7ers9gtnh4580xj89zdjuew9nqhxywmsaw94fs5udupc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM1hNQkJHcDUxbkQwM0NE
            Y0pQRGE5QUdGQW5Bak5icE5jbjhlczQrU3o4CmdvVVlvNkVWQ3ZoU1JvOXkxekRr
            enZTN2M0aVhwQzRDaTREaDI1OTR3RlUKLS0tIFR6WnB5Mzh6QkxaWnlFVFF1N1lO
            d0svWEdVdnhxM3RxdGNOVm1qYkt3UjQKj/a8b8cnIekk+nIuqFxld38uWf9wl5G1
            p5vTB4hv93l5VCFL3ipHYV1kA+nXUvAMleg8k12MgLs5FWQvfKbuGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNW1UL09rems5K2RWdWRR
            VktyU1lKdDRRbEIzVmFMRXAxU2hFU25KVEJ3CjhOcDY5NEdyak1LQTFzeTkyTzdY
            Nk1XbURVR1RiMkNQYnBpMFlidDBHd00KLS0tIGZ3djBacUorOFZxUjQ1alJicFlX
            THFjSEI1SndHSDEwRng4MldmZTFST3MKw0T4QkxAiBib9Xozc9QYA/4AdRT3oPIf
            uKpPs4ADI7RFAvrdmwDzJlTwf77e4VA+ZWT6TaxLfk6LcsHXycT1HA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7tfjwzp6dxwkw9vej6knkhdvqre3fu7ryzsdk5ggvtdx854ycqevlwnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3czZ2QUU1cTU4YnhBK0tG
            Vkc4VHJnS0V5eUJWcGQ4QkljOFpvMkxpRDNzCjEzQW5UZ0RseWkwTXJ2THJ0dUti
            RUJua1M2dXpPd1ZHQ1FWV1hjdklEcXMKLS0tIElkVnZsMVR4cU5IOU4zdTNlRzcr
            aGhzWUtaY3NVbnBtSkh6bUxRYlBHZU0KVQgEX1tBiE5Yiipzo7CFnLb0YO4BCqWa
            ZIttlq2lW1oxivpk6KPUg+aLCOIgyLEPkOuYIw9XNeT/t47m0GJIYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr4suv4lhtt8f59s25eukdfk67j7av72gvj7sk7ux6thusct3utqmn3pmf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL3FadFlhVExKemlsVWxv
            Q2J1eVArbW9OZzlMcTNRQitvc2lQRkNWb0ZjCjdoZkFhaWxFUElIeVFaUWRpQmlT
            QnRJWW5icGxKZlhJZmp0SVU5dHpTSmMKLS0tIE12dERYVGpwTzhMRFkwNytZQkVS
            MFlJekswK2pkV3lzVGhqRitpMDY0SmcKRaW/wm6SIJBX514g4zZD2k4k0kSzQ4qA
            baNRlr1fqj3LjIzWBlwolmM+W3cTyhVV8VSjN8fZ+xQcVPjSFazB6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-25T19:43:46Z"
    mac: ENC[AES256_GCM,data:ZQibKAevbsldaAIjzoZ4/zzWdCLaGHKMzBU7zre6DnE+9UF3vpa+VWfTPCs7ovqKkWJUsTiyyg8JxMeF3ivFnXRzrbzeX5EZRAqlKQJHXAp5ruWDJL5Zaw3dWMVM70MGJDOsZdws5tJUu8jbZN5nYX+yjw1zDIfb1Gho7sfYg48=,iv:VDP2iWxiFy+4vTQd5DKMNpMFAWrfwKKaGfZos+Y5l3U=,tag:wo8a27b6hWkL85e+IIm58Q==,type:str]
    pgp:
        - created_at: "2021-09-29T17:02:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3tEuTsG48KkAQgAl3H+gXJ1Q4sRM6keLtiAO8Irf2ZHqLq1/CyzkJXymfXf
            rme3cssXfuxfn2mPDPUb7eLOVtrv8vWuMkAripHJvzKNSyxf6fEbFZlN2zT48AZA
            E8UYV5/pHSXQ5tmVhOMUuWJBThvOoogBHNEzZVCqdd28ZK7utqU3ynSe08KQWAHO
            /VEa//so3sr21vLg32LZzTPqdzjFQjLPnvvqQ0ItghbzsIiTsjy40jAF5+jSwX49
            BND9+tI3GJgg/bppiSLhAk6NVW6TRu5UoJQ/CxMsj79FPyUoyU9cb8ub74CvNaJy
            Hjz5JEArIo8qRj+peQ7OqsNJfuqyM/+tgzJOc9Li4NJeAdVuVTrYeqHt44B5TEO+
            S3zEb0BeDra8Ol2qIPLlWvuTH7s45xHDni9cB95usC6QIvLenO7tbBT8QjpKIguw
            qJS6ei6uVaeTdz3T2FNlqEEDh3avD5558mAK8iz3NQ==
            =V6ae
            -----END PGP MESSAGE-----
          fp: 260353B993F8CE16752EF48C71BAF6D40C1D63D7
    unencrypted_suffix: _unencrypted
    version: 3.7.1
