nix-community-cachix: ENC[AES256_GCM,data:tGMaYSBnhZ9idMV7DGzUfR1Zzk70syR8f4DSkrO65XcYUvoS4tcaVXr4l6PzDAFetkgU92a/kkIrEMZ9tZZZGHMvmCteGObH2BgF6k57NdozNnkXsI4ZhltATu5tpwzI+DUFgtpAXPEVYY6DRDlUATrt8SKJ2JuI4JtpIHpPi0noS/WpBfsphOUQ/7epTtABLpyDb0EOXisvkPLjDIKwfNDE+dOHO61aN8zS14QhelRIfJUSj7BwVFWbaseLKmq5ZIDAFK5s/FSgToi4Bj/YYVrTo23RH8wvhYOelSNcAWW/wotMZ5u/pklTytytLC41DhyFXU54k/UEorfVMHMnLAlujDoBs/9oV+M18Jcs0qV7c1utzjwoGlYhxV7zV/QvJ2zuMyDtszK0twcL8BjUSpsy+W/sR3kpGBKzjt1oNteTlz0YvIXlxg/Yn63qGr2/HzZlNd9rygMnLhTf7VO4Su2AB4GLXI7ljgQdqM7AREuAgE5J0hHE82fRalBsZcK34QGEFVKN4mzybcK4HO70yUQY4o5cOc7R5DHvEJmukjjJclm/,iv:N/yKtyd56YpdpNEe92g9Eml8gYR9x5pBT66U5p20Rzw=,tag:HCAJSqQ3Wq5SnZDwdryN1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY0JoN3JhSGN1NXR6T3FP
            MEFvZjYrTlNGSGQxa0tSclRXMENzTnIzVEc0ClV0aWxHblRmaENzNWpTWlFnSnNq
            TDJkZEx3N3Z3YnB4M0svOWxNZHhveFkKLS0tIGllSmVvM2ZoM1ZEYkh6b2xFdFBC
            NWJqSytVYnNTOXIyaHZpYThncUVoa0kKtwDgPXI0KHGOT3CEMUpNSD+F57jG27Ya
            hLJzSgGZq29q7U1xWsvS8VbVBmpmL7MMTzmmpqCrE1/SFxGJlcjBwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d87z3zqlv6ullnzyng8l722xzxwqr677csacf3zf3l28dau7avfs6pc7ay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVDY4MWQwVXZ2RFQxTDNx
            TVJNZUFwSUZkUjAzM3VhVldlWkZrZWEzOWlBCkF1SVpNSWU5Y3lpZERMR083VDdw
            dzBOaXN5MXArOGlNdW1BSkhLUkd4WW8KLS0tIHlRMnhab1phVDl4c2NFNnU3d1FL
            YmdCSDVOalFMdFlVUkFTUEFJc1J1azQKk4QBdhwtC8KTKFc6huRjzlnvSj8qGV8S
            Ix0izRiqmMQv5VB/Ij9LPQ8hoX0E/IQQVcjve+/AsUAeB/PLYxhUMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17jtyn2y4fpey6q7ers9gtnh4580xj89zdjuew9nqhxywmsaw94fs5udupc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSWdSQjgyU0JTaDRFZGtW
            OTRrVitNMUtRKzkwc2tBcEF4TlFQaHQ2c0NvCk5ZODVvZHVRMXlqcmU2N3BMMEtN
            UkpWczk3RTFpbU4vdmNqbUF6bHNNbE0KLS0tIGNibDFhd1ljMjRMZmY1TzhBcU5M
            UlJNamYzMUViMTE3Y1pvaXZGbEQ0RGMKCgtAW8SMwiSDQlhh1ha6ZkDnxt8bN0Xe
            L5yr3s8BsUQjEz7KoEOK+WTaoZ3oQNVpbk1U4Yltb/HRTNEJKSKAtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kh6yvgxz9ys74as7aufdy8je7gmqjtguhnjuxvj79qdjswk2r3xqxf2n6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZHlVL0tMZ2JXZ2Vod2lY
            Qy9MYXBVU2hHUDFINWJSb2xkRERVdnh1VERrClovVWFBQkdSWFFiYU5MemR0eHJv
            Uzd3Y0lyQWlsMEVRZVRMYXFyQ3Z5ZGcKLS0tIDR3Yk5ORmhMcWJVNXEyYnVTNVJX
            U0FLQlNhNnFhVjhtM3R6alVrMHRiNGMKog6V1r10mO/GkhgDmmQ3/aygSwKE3Vsv
            n8fOhFI88B5/u/mpj7djcUgGS6lwycFzvsgvBluYQPyCjc63uf6cUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7tfjwzp6dxwkw9vej6knkhdvqre3fu7ryzsdk5ggvtdx854ycqevlwnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU2Z4eTFhZ2RKb2twZm81
            ZytJeVlmMVc4M2QyQVVZd2hyK0hGRkl6Z1gwCitTMHlVKzJ2R1dZdjI0U2VqbW5O
            KzZaTGVSV2s2SGFka2pMc1o0eExRdjgKLS0tIFlsM093Q2N2c3h3NjFkNkJUb0p3
            SStDR0xpSjdYMVpldXNCdHcxMXlxOEUKTBHKXG7kPlr9u3Qz4XmeSbtN1QwwnZxZ
            C0vFttW+JZvUx+7eepFhyIQK/VJCgJMr8+Q7tloJb+jTAYgetaNUGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r2t5vf67jay42ju8r6d47q6zssxvv9jjh8k42qequnnsfjjk632qm2tfrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ3I1dXdkdjdMRVV4dXp4
            OGlSeVBMVnZUcE9ZMzhaTmR3VjZXc2xFdTJ3CmtLTDRhRjhLWjh5aHJIVEJMTmtu
            TXJycWkyYkZmOGFUNUhQdGlidUNyNjAKLS0tIGJldEFRbGZJcDI3N2V3YWFoVTdz
            c3l2MHRxSXdSQlpOSmdBckRBdmV3SzQKlcr78Aij13N0FdWnoRYTrNav7yLF/wSD
            OxTMazFi32mKzfDnvfuZnM+u+OKOzctl+SNrqyIYfvtFlfiG9nCuwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m7xhem3qll35d539f364pm6txexvnp6k0tk34d8jxu4ry3pptv7smm0k5n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVjE0Z004dWdmR0F2ekRv
            T2RQcHhheXFXNWc1bncwRkNSbTNYMmxlZnpFClpKM0VYaTZ6MVRLZGRLMmUzYWdM
            L1F6UTZlNzN5cnJqakNPTmpqNVN3T0kKLS0tIERnYlRMdE4vY3g2eWdwc2h3NVgv
            MjZwY1VQUmF2V01WWnFsK2prZ0YvK0EK5z3k5V9L5s2Xf2vH/9bBlOZ4G/iheLgz
            TD9jIVjJsgqcTRalFqf9WYNGFRzhEhApDiIic3zMpy0LH6xIMHUwTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-25T19:43:46Z"
    mac: ENC[AES256_GCM,data:ZQibKAevbsldaAIjzoZ4/zzWdCLaGHKMzBU7zre6DnE+9UF3vpa+VWfTPCs7ovqKkWJUsTiyyg8JxMeF3ivFnXRzrbzeX5EZRAqlKQJHXAp5ruWDJL5Zaw3dWMVM70MGJDOsZdws5tJUu8jbZN5nYX+yjw1zDIfb1Gho7sfYg48=,iv:VDP2iWxiFy+4vTQd5DKMNpMFAWrfwKKaGfZos+Y5l3U=,tag:wo8a27b6hWkL85e+IIm58Q==,type:str]
    pgp:
        - created_at: "2022-12-30T19:49:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3tEuTsG48KkAQf9GKFJ1P0owIl+VzdIdHGHYZsk+vmqe1i02iEwj3nulO/U
            ghCdDVXSYd4mkAjYdeRgKGojBtLsKSa3kN6bocuXGaBripYZcRN0+Dvx0F//Wkjl
            k8PGCg6rhRp7fY17p3SvOdwM70vF0+ol2wGgru5hY8e4hHki4OBnaDL08uDJiiIa
            VKzpaFbFGrKebDnu1pj12Nffqwp5WuZWnXF13lsv/jjWuK2KH5ixr4cgXUPIHOfL
            LIKDqc/5Wv/qn0Fia8YIPupyDE9oNucvovZG6b0sLX7KmGkuI18P6QkozckQ+y6R
            fVu3t8nNl7WKDQhcx2WIqehhQgCpZ7a5FLFX/N+LFtJeARN4PReypd1GaeM3CcDl
            2V2Ynn2X+sRAzb/vsYBpK4uPgUfvC3e6kDaBfy/nT9QjVABfqoGyMv2FEr7Z5Llp
            m43FaQIhWh/J/R51nqhJsZQyKwsSrkhWjv4JVnjjuw==
            =qdWF
            -----END PGP MESSAGE-----
          fp: 260353B993F8CE16752EF48C71BAF6D40C1D63D7
    unencrypted_suffix: _unencrypted
    version: 3.7.1
