nix-community-cachix: ENC[AES256_GCM,data:tGMaYSBnhZ9idMV7DGzUfR1Zzk70syR8f4DSkrO65XcYUvoS4tcaVXr4l6PzDAFetkgU92a/kkIrEMZ9tZZZGHMvmCteGObH2BgF6k57NdozNnkXsI4ZhltATu5tpwzI+DUFgtpAXPEVYY6DRDlUATrt8SKJ2JuI4JtpIHpPi0noS/WpBfsphOUQ/7epTtABLpyDb0EOXisvkPLjDIKwfNDE+dOHO61aN8zS14QhelRIfJUSj7BwVFWbaseLKmq5ZIDAFK5s/FSgToi4Bj/YYVrTo23RH8wvhYOelSNcAWW/wotMZ5u/pklTytytLC41DhyFXU54k/UEorfVMHMnLAlujDoBs/9oV+M18Jcs0qV7c1utzjwoGlYhxV7zV/QvJ2zuMyDtszK0twcL8BjUSpsy+W/sR3kpGBKzjt1oNteTlz0YvIXlxg/Yn63qGr2/HzZlNd9rygMnLhTf7VO4Su2AB4GLXI7ljgQdqM7AREuAgE5J0hHE82fRalBsZcK34QGEFVKN4mzybcK4HO70yUQY4o5cOc7R5DHvEJmukjjJclm/,iv:N/yKtyd56YpdpNEe92g9Eml8gYR9x5pBT66U5p20Rzw=,tag:HCAJSqQ3Wq5SnZDwdryN1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUWpQcmZzSVlUd21oTDJB
            Y0RkVG9XUVptSmNVNlRkVFZNYkxuQXNyZjJjClRYVHoxS1NJRjlheCtRQ3V5OW4w
            ZXA4Ym1SSzJJR3NhUkRmMWViNCtVNjgKLS0tIFBKVUZCQkNQN1h3aGovUTd1bWhz
            bUlsY1RyWDMyYlU0aGQ0ZElrT3RDd3MKrCIdWzknV9TguuSkCn6gPVxSX2uYfwnA
            eRkGVpuMA9FlytwBMg+QV5JN3Kgi2MZ5Ap1dtP72AbVbQucc+M6YgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d87z3zqlv6ullnzyng8l722xzxwqr677csacf3zf3l28dau7avfs6pc7ay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Nnc5MkVQNTlwcmdrWUFL
            RmJVZVFHaW5oM3VpcmUrTmhqaDNTcUxVNkRnCjAwdGpZbjE2cDZlUGErbCtKV0k4
            dWRSYjEwVHVRNk4rSWJkeDNwamg0TU0KLS0tIC9US3pzSnlCSm9zVWU2TGUwOXZl
            VDh2cktFMklxOWpCRU1XMTE0MVd6ZVkKJMRw66azUgibl27J7FzJ8WXT/hqwvfrz
            FDFKXCWG06XMYZPPFUXqnnACqT2CvYlAqS0QQg+90Y4LRYJgCJofCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17jtyn2y4fpey6q7ers9gtnh4580xj89zdjuew9nqhxywmsaw94fs5udupc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdDYvRm1DZlAweDJJcDBB
            RUEwb3lpSXFrdDdZNDhqdS92M1h1TS8wSDJzCmdwaEFMZ3E1RjFObllpN0MwNGc2
            RDQ5d05nNDMvV2k1MW5BMHVVSUN5ek0KLS0tIGs0ckZROFRpWkhBYngyWkNxTmtT
            MjRDK01vcmMrQzFJd1VPSFpsVFkzR3MK4knio/OIqUK3jOwBBfpSlxU7Cd24NtcX
            M7eFeL4dELJp7tz2Sa+G8wPqfd0+5LqBFm6btCPghRyJh6hauBDE9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kh6yvgxz9ys74as7aufdy8je7gmqjtguhnjuxvj79qdjswk2r3xqxf2n6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSURtaXU3bEpncEFNbThR
            L1R2Um9rN0lPYlZOOVhBd1BEdjhQUUZOVW44CndCaEVvUlNlRXZUaTUvZkRLSktl
            ODJ5OUd6a2Q4S2ZkSjkwaXIrbWZwd0EKLS0tIG5CV3ZQMnFaaHRaVU1kTHlXMXFo
            TndBOXdkUHN5VmMvS3VaOUw1aDFGOXMK31KLw7VuibqnfBSMjjv9fl1PF+JfqJy8
            bj3Cg4+g88JUp1o8KxmdSSdKk2o+QsyzExPPXKzJjG73hutvvYELQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7tfjwzp6dxwkw9vej6knkhdvqre3fu7ryzsdk5ggvtdx854ycqevlwnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVHovdGhiQXVzSHlpVGVs
            Q3hrR1k2VDNKZWFtNHl1U2RwbUU0RU9kRlhrCjBkSW1TeVc0YnplSEF4b20xWjNk
            OTVVeitYOVdMd0M3MXRWNkZWVTkrb1kKLS0tIGs1T2R1bTR2ei9Hc2V1U3NiNFJ6
            L2RuamlmLzhrdFVIcHlqYU14QnJNVWcKSbl3NijlG/pcknA6djt/UH73axyNBIJF
            TCXMrUZl23bx1hiQsIMH7k5IogQWxaWcrjsgoK4zBDpKlZ3CK2KLmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr4suv4lhtt8f59s25eukdfk67j7av72gvj7sk7ux6thusct3utqmn3pmf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaDZxSU8wazlxY1BNNjBM
            S2JoenFFSExrc3htSFJhV0lJTll0Y3hxMWswCnU4dnVyd0FqREpIZWhmS3dSanlS
            TUthNnRDampMTWZyaVBzYThsVUtzaEUKLS0tIFErWElsR05oQW50cFVtaFhtUVky
            RjE1Z0ExQjJ1Q0ZHa0hwNTVTb1VFTWcKKQtu7iOLTGGDCtn843CGeSKWAecD9C5x
            i4wDgyw8EO44RpqES2wBQhqE8uBYMv8YvwuQIeXplmQNcjsNDvO2fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m7xhem3qll35d539f364pm6txexvnp6k0tk34d8jxu4ry3pptv7smm0k5n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMSsydzB6MkFvSElFdG1l
            aTJsNVhGNWFTZFJJTUNreDlobFF3cS9kemxjCkhqNU9USXZPY1pQQVordElrdytC
            NFIrcGN4VHp6RzdNZ2t3OXRtSHA2STgKLS0tIGVOaHUyVmRGZk9UcmpNRFBmVWdz
            NG5oSkFOcmtJSzV5cXdpanlkVWdSbTgKKW9+7+p6K0o915X5uz9h/76aPxBsPkjJ
            TMySL9YvhPqWER5IVPCHEdHtXpjtqhVfPxouoXo0iK8fT3fhfY6qWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-25T19:43:46Z"
    mac: ENC[AES256_GCM,data:ZQibKAevbsldaAIjzoZ4/zzWdCLaGHKMzBU7zre6DnE+9UF3vpa+VWfTPCs7ovqKkWJUsTiyyg8JxMeF3ivFnXRzrbzeX5EZRAqlKQJHXAp5ruWDJL5Zaw3dWMVM70MGJDOsZdws5tJUu8jbZN5nYX+yjw1zDIfb1Gho7sfYg48=,iv:VDP2iWxiFy+4vTQd5DKMNpMFAWrfwKKaGfZos+Y5l3U=,tag:wo8a27b6hWkL85e+IIm58Q==,type:str]
    pgp:
        - created_at: "2022-10-25T07:54:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3tEuTsG48KkAQgAnMbguVBAEO19J2Fb0BKSY22ka89gaA1o0Dh8m9Ne9HfD
            vDhv0A89F9sKUK/E659FJxXkDdXo4RGFF26oitylntaVMLpLFeTO4IGDe6ybZRvC
            2dOiePsaogqai1K3075jThOdm/gXnql32e3KdjVs8+54F2afLZHtB36u1NK3A0My
            3MdxEW3QKE5bJsg+0pEkz2DeIr9A7KSKYMI7cDVC61V1MX7q2E+LDkhARl8VX327
            jYyJVIkOepcZfWpVdcHfsRbJL6QrVm9ZaKAM0k0n1dhZeij0Q7Ie/qLHlWwpc8Df
            N/oZi4ykt0LWxh8ncZ4bPvyLbh6esQ1g5rNGFaKOMdJeAWL01oqobTCFy+0nO+ie
            viYgjbAPmlrqRlkTTHv1h3x0s261BXEemm1BmiRPVoE9a+vzL11Nxi7zyGAamLHJ
            cMtkhAaJ+fZxP7rIzg1NkqtOhED2JorgngMO45Y7Og==
            =DJEv
            -----END PGP MESSAGE-----
          fp: 260353B993F8CE16752EF48C71BAF6D40C1D63D7
    unencrypted_suffix: _unencrypted
    version: 3.7.1
